---
name: PDF-FDF-Simple
version: 0.19
author:
  - 'Steffen Schwigon <ss5@renormalist.net>,'
abstract: Read and write (Acrobat) FDF files.
license: perl
resources:
  repository: git://github.com/renormalist/pdf-fdf-simple.git
requires:
  Class::Accessor::Fast: 0
  Compress::Zlib: 0
  Parse::RecDescent: 1.94
  Test::More: 0
  perl: 5.6.1
provides:
  PDF::FDF::Simple:
    file: lib/PDF/FDF/Simple.pm
    version: 0.19
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
