---
name: PDF-FDF-Simple
version: 0.16
author:
  - 'Steffen Schwigon <ss5@renormalist.net>,'
abstract: Read and write (Acrobat) FDF files.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0
  Parse::RecDescent: 1.94
  Test::More: 0
  perl: 5.6.1
provides:
  PDF::FDF::Simple:
    file: lib/PDF/FDF/Simple.pm
    version: 0.16
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
