=pod

=head1 NAME

TestHelper - Class for __

=head1 extends L< Exporter | Exporter >

Z<>

=head1 SYNOPSIS

my $obj = TestHelper->new ({paramhashref});

=head1 Methods

=head2 not_ok

DESCRIPTION

__

ARGUMENTS

__

RETURN

__

=head2 ok

DESCRIPTION

__

ARGUMENTS

__

RETURN

__

=head1 AUTHOR

  Written 2002 by Steffen Schwigon <schwigon@webit.de>.

=cut
